# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename) {
    .Call('_Seurat3_0_RunModularityClusteringCpp', PACKAGE = 'Seurat3.0', SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput, edgefilename)
}

RunUMISampling <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_Seurat3_0_RunUMISampling', PACKAGE = 'Seurat3.0', data, sample_val, upsample, display_progress)
}

RunUMISamplingPerCell <- function(data, sample_val, upsample = FALSE, display_progress = TRUE) {
    .Call('_Seurat3_0_RunUMISamplingPerCell', PACKAGE = 'Seurat3.0', data, sample_val, upsample, display_progress)
}

RowMergeMatrices <- function(mat1, mat2, mat1_rownames, mat2_rownames, all_rownames) {
    .Call('_Seurat3_0_RowMergeMatrices', PACKAGE = 'Seurat3.0', mat1, mat2, mat1_rownames, mat2_rownames, all_rownames)
}

LogNorm <- function(data, scale_factor, display_progress = TRUE) {
    .Call('_Seurat3_0_LogNorm', PACKAGE = 'Seurat3.0', data, scale_factor, display_progress)
}

FastMatMult <- function(m1, m2) {
    .Call('_Seurat3_0_FastMatMult', PACKAGE = 'Seurat3.0', m1, m2)
}

FastRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_Seurat3_0_FastRowScale', PACKAGE = 'Seurat3.0', mat, scale, center, scale_max, display_progress)
}

Standardize <- function(mat, display_progress = TRUE) {
    .Call('_Seurat3_0_Standardize', PACKAGE = 'Seurat3.0', mat, display_progress)
}

FastSparseRowScale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_Seurat3_0_FastSparseRowScale', PACKAGE = 'Seurat3.0', mat, scale, center, scale_max, display_progress)
}

FastSparseRowScaleWithKnownStats <- function(mat, mu, sigma, scale = TRUE, center = TRUE, scale_max = 10, display_progress = TRUE) {
    .Call('_Seurat3_0_FastSparseRowScaleWithKnownStats', PACKAGE = 'Seurat3.0', mat, mu, sigma, scale, center, scale_max, display_progress)
}

FastCov <- function(mat, center = TRUE) {
    .Call('_Seurat3_0_FastCov', PACKAGE = 'Seurat3.0', mat, center)
}

FastCovMats <- function(mat1, mat2, center = TRUE) {
    .Call('_Seurat3_0_FastCovMats', PACKAGE = 'Seurat3.0', mat1, mat2, center)
}

FastRBind <- function(mat1, mat2) {
    .Call('_Seurat3_0_FastRBind', PACKAGE = 'Seurat3.0', mat1, mat2)
}

FastExpMean <- function(mat, display_progress) {
    .Call('_Seurat3_0_FastExpMean', PACKAGE = 'Seurat3.0', mat, display_progress)
}

SparseRowVar2 <- function(mat, mu, display_progress) {
    .Call('_Seurat3_0_SparseRowVar2', PACKAGE = 'Seurat3.0', mat, mu, display_progress)
}

SparseRowVarStd <- function(mat, mu, sd, vmax, display_progress) {
    .Call('_Seurat3_0_SparseRowVarStd', PACKAGE = 'Seurat3.0', mat, mu, sd, vmax, display_progress)
}

FastLogVMR <- function(mat, display_progress) {
    .Call('_Seurat3_0_FastLogVMR', PACKAGE = 'Seurat3.0', mat, display_progress)
}

RowVar <- function(x) {
    .Call('_Seurat3_0_RowVar', PACKAGE = 'Seurat3.0', x)
}

SparseRowVar <- function(mat, display_progress) {
    .Call('_Seurat3_0_SparseRowVar', PACKAGE = 'Seurat3.0', mat, display_progress)
}

ReplaceColsC <- function(mat, col_idx, replacement) {
    .Call('_Seurat3_0_ReplaceColsC', PACKAGE = 'Seurat3.0', mat, col_idx, replacement)
}

FindWeightsC <- function(integration_matrix, cells2, distances, anchor_cells2, integration_matrix_rownames, cell_index, anchor_score, min_dist, sd, display_progress) {
    .Call('_Seurat3_0_FindWeightsC', PACKAGE = 'Seurat3.0', integration_matrix, cells2, distances, anchor_cells2, integration_matrix_rownames, cell_index, anchor_score, min_dist, sd, display_progress)
}

IntegrateDataC <- function(integration_matrix, weights, expression_cells2) {
    .Call('_Seurat3_0_IntegrateDataC', PACKAGE = 'Seurat3.0', integration_matrix, weights, expression_cells2)
}

SNNAnchor <- function(k_matrix, anchor_only) {
    .Call('_Seurat3_0_SNNAnchor', PACKAGE = 'Seurat3.0', k_matrix, anchor_only)
}

ComputeSNN <- function(nn_ranked, prune) {
    .Call('_Seurat3_0_ComputeSNN', PACKAGE = 'Seurat3.0', nn_ranked, prune)
}

WriteEdgeFile <- function(snn, filename, display_progress) {
    invisible(.Call('_Seurat3_0_WriteEdgeFile', PACKAGE = 'Seurat3.0', snn, filename, display_progress))
}

DirectSNNToFile <- function(nn_ranked, prune, display_progress, filename) {
    .Call('_Seurat3_0_DirectSNNToFile', PACKAGE = 'Seurat3.0', nn_ranked, prune, display_progress, filename)
}

